export const gitUpstreamMutationCommands = [
  "git branch -u origin/main main",
  "git branch -uorigin/main main",
  "git branch --set-upstream-to origin/main main",
  "git branch --set-upstream-to=origin/main main",
  "git -C ./repo branch -u origin/main main",
  "GIT_DIR=.git /usr/bin/git branch --set-upstream-to=origin/main main",
  "git -c alias.branch=!bad branch -u origin/main main",
  "git push -u origin main",
  "git push -vu origin main",
  "git push --set-upstream origin main",
  "git push origin main --set-upstream",
  "echo ready && git push -u origin main",
  "git branch -u origin/main main; echo done",
  "env git push -u origin main",
  "command git branch --set-upstream-to=origin/main main",
  "sudo git push -u origin main",
  "(git push -u origin main)",
  'sh -c "git branch -u origin/main main"',
  "bash -lc 'git push --set-upstream origin main'",
  "git branch --unset-upstream main",
  "git config branch.main.remote origin",
  "git config --local branch.main.merge refs/remotes/origin/main",
  "git config --unset branch.main.merge",
  "git config unset Branch.main.Remote",
] as const;

export const nonGitUpstreamMutationCommands = [
  "git push origin main",
  "git branch main",
  "git branch --track feature origin/feature",
  "git switch --track -c feature origin/feature",
  "git checkout --track -b feature origin/feature",
  "git config --get branch.main.remote",
  "git config branch.main.remote",
  "git config unrelated.setting value",
  "git remote set-head origin -a",
  'printf "git push -u origin main"',
  "echo 'git branch -u origin/main main'",
  "git config --get-regexp 'branch.*.remote'",
] as const;
